FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

ENV ANTHROPIC_API_KEY=''
ENV POSTGRES_DB=''
ENV POSTGRES_USER=''
ENV POSTGRES_PASSWORD=''
ENV POSTGRES_HOST=''
ENV POSTGRES_PORT=''
ENV SOURCE_DATA_DIRECTORY=''
ENV SOURCE_THUMBNAIL_DIRECTORY=''

CMD ["streamlit", "run", "image_retrieval.py", "--server.port=8501", "--server.address=0.0.0.0"]
